import { Bebas_Neue, Poppins } from "next/font/google";
import "./globals.css";
import SmoothScrollProvider from "@/lib/smoothScroll";
import { Analytics } from "@vercel/analytics/next"
import ChatBot from "@/components/ui/ChatBot";
import BotButton from "@/components/ui/BotButton";


const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: "400", // Add this line

});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Add this line
});

export const metadata = {
  title: "Rotaract 3220",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${poppins.variable} antialiased`}
      >
        <Analytics />
        <SmoothScrollProvider>
        <div>
          <BotButton/>
        </div>
        <div className="z-60 fixed right-0 top-0">
          <ChatBot/>
        </div>
        {children}

        </SmoothScrollProvider>
      </body>
    </html>
  );
}