

export const metadata = {
  title: "District Portal | Rotaract 3220",
  description: "Generated by create next app",
};



export default function aboutLayout({ children }) {
  return (
        <div>
        {children}
      </div>
  );
}